//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public int id { get; set; }
        public int idCu { get; set; }
        public int idUs { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
