//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajes
    {
        public mensajes()
        {
            this.puntuacionChat = new HashSet<puntuacionChat>();
            this.Respuestas_Chat = new HashSet<Respuestas_Chat>();
        }
    
        public int id { get; set; }
        public int idSe { get; set; }
        public int idUs { get; set; }
        public int estado { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual sesiones sesiones { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<puntuacionChat> puntuacionChat { get; set; }
        public virtual ICollection<Respuestas_Chat> Respuestas_Chat { get; set; }
    }
}
