//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        public Preguntas()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int Id_Preguntas { get; set; }
        public string Texto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Usu { get; set; }
        public Nullable<int> conteo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
