//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntuacionRes
    {
        public int id { get; set; }
        public int idRes { get; set; }
        public int IdUs { get; set; }
    
        public virtual Respuestas_Chat Respuestas_Chat { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
