//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.V.WantHelp_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas_Chat
    {
        public Respuestas_Chat()
        {
            this.puntuacionRes = new HashSet<puntuacionRes>();
        }
    
        public int id { get; set; }
        public int idSe { get; set; }
        public int idChat { get; set; }
        public int idUs { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual mensajes mensajes { get; set; }
        public virtual ICollection<puntuacionRes> puntuacionRes { get; set; }
        public virtual sesiones sesiones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
